# Generated by Django 3.2.16 on 2022-11-24 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_reservationVol', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compagnies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=250)),
                ('image_path', models.ImageField(upload_to='compagnies')),
                ('status', models.CharField(choices=[('1', 'En service'), ('2', 'Hors Service')], default=1, max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Liste des compagnies',
            },
        ),
        migrations.CreateModel(
            name='Trajet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depart', models.CharField(max_length=250)),
                ('arrive', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('1', 'En service'), ('2', 'Hors service')], default=1, max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Liste des trajets',
            },
        ),
        migrations.CreateModel(
            name='Vols',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=250)),
                ('status', models.CharField(choices=[('1', 'Disponible'), ('2', 'Indisponible')], default=1, max_length=2)),
                ('prix', models.IntegerField()),
                ('date_depart', models.DateTimeField()),
                ('date_arrive', models.DateTimeField()),
                ('compagnies', models.ManyToManyField(to='app_reservationVol.Compagnies')),
                ('depart_trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depart_Trajet', to='app_reservationVol.trajet')),
                ('destination_trajet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arrive_Trajet', to='app_reservationVol.trajet')),
            ],
            options={
                'verbose_name_plural': 'Liste des vols',
            },
        ),
        migrations.RemoveField(
            model_name='flights',
            name='airline',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='from_airport',
        ),
        migrations.RemoveField(
            model_name='flights',
            name='to_airport',
        ),
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name_plural': 'Liste des réservations'},
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='address',
            new_name='addresse',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date_added',
            new_name='date_ajoute',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='date_created',
            new_name='date_cree',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='first_name',
            new_name='nom',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='last_name',
            new_name='prenom',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='status',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='type',
        ),
        migrations.AddField(
            model_name='reservation',
            name='genre',
            field=models.CharField(choices=[('Homme', 'Homme'), ('Femme', 'Femme')], default='Homme', max_length=50),
        ),
        migrations.AddField(
            model_name='reservation',
            name='status_reservation',
            field=models.CharField(choices=[('0', 'En cours'), ('1', 'Confirmé'), ('2', 'Annulé')], default=0, max_length=2),
        ),
        migrations.DeleteModel(
            name='Airlines',
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
        migrations.DeleteModel(
            name='Flights',
        ),
        migrations.AddField(
            model_name='reservation',
            name='vol',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app_reservationVol.vols'),
        ),
    ]
